/* ============================================================
   cosmos.js : code emitters

   Turns the current settings into a standalone program in Python
   or JavaScript that draws the same planet the preview is drawing.
   Both exports are self-contained: no imports beyond the standard
   library, no dependency on this app.

   Only what the settings actually use gets written out. A smooth
   moon with no rings emits neither the bisection search nor the
   ring compositing, so the file stays readable instead of shipping
   every branch of the renderer.

   Two things must hold or the exports drift away from the preview:
     - derived seeds are computed HERE and baked in as literals, so
       neither language has to reproduce JavaScript's int32 xor
     - Python rounds half to even, JavaScript rounds half up, so the
       ramp index uses int(x + 0.5) rather than round(x)

   ------------------------------------------------------------
   HOW TO READ THIS FILE
   Each emitter builds up an array of source lines and joins it at
   the end, so reading python() from top to bottom reads the
   generated program from top to bottom. The `if (p.rock)` and
   `if (p.rings)` blocks are the parts only some planets need.

   Nothing here parses or rewrites the renderer. The exported code
   is a hand-written second copy of it, which is the trade: the
   output stays readable enough to paste into a project, at the
   cost of having to be kept in step by hand.

   ADDING A TEXTURE
   The albedo function exists three times over, once live and once
   per export, so all of these change together:

     1. planet.js  TEXTURES.<name>       the live preview
     2. emit.js    texturePy()           the Python export
     3. emit.js    textureJs()           the JavaScript export
     4. emit.js    parts()               which feature tables it needs
     5. app.js     SPEC texture options  so it can be picked
     6. app.js     the Randomize list    so it can come up by chance

   Nothing throws if one is missed. The export simply stops matching
   the preview, and only a careful look at both will say so.
   ============================================================ */
var Emit = (function () {
  'use strict';

  /* --- literals --------------------------------------------- */

  /* A float, trimmed so the emitted source reads like something a person
     wrote, without losing precision that would move a glyph. The trailing
     ".0" is not decoration: it keeps a value that happens to land on a whole
     number reading as a float in both languages. */
  function n(v) {
    var s = (Math.round(v * 1e6) / 1e6).toString();
    return s.indexOf('.') === -1 && s.indexOf('e') === -1 ? s + '.0' : s;
  }
  /* An integer: counts, grid sizes, seeds. */
  function i(v) { return String(Math.round(v)); }

  /* The seeds the renderer derives with xor. JavaScript's ^ works on int32 and
     can hand back a negative number, which the PRNG then reads as unsigned;
     Python's ^ never does. Resolving them here means the exported code just
     sees a plain positive integer. */
  function seeds(c) {
    return {
      craters: (c.seed >>> 0),
      maria:   ((c.seed ^ 0x9E3779B9) >>> 0),
      cracks:  ((c.seed ^ 0x51F0AA) >>> 0),
      shape:   ((c.seed ^ 0x51F0AA) >>> 0),
      facets:  ((c.seed ^ 0xA33C17) >>> 0),
      knobs:   ((c.seed ^ 0xB0C1D2) >>> 0)
    };
  }

  /* Which pieces this configuration actually needs. Each flag switches out
     both a table and the code that reads it, which is why a smooth ringless
     moon exports a file roughly half the length of a lumpy ringed one. */
  function parts(c) {
    var t = c.texture;
    return {
      rock:    (c.lumpiness || 0) > 0.001,
      rings:   !!c.rings,
      craters: t === 'cratered' || t === 'ice' || t === 'rock' || t === 'lava',
      maria:   t === 'cratered' || t === 'ice' || t === 'desert',
      cracks:  t === 'ice' || t === 'lava'
    };
  }

  /* ---------------------------------------------------------- *
     Python
     ---------------------------------------------------------- */
  /* Takes the settings and the body built from them: the frame size and the
     bounding radius are worked out during Cosmos.build(), and are baked in
     rather than recomputed by the export. Returns the finished source. */
  function python(c, b) {
    var s = seeds(c), p = parts(c), L = [];
    var rgb = hexToRgb(c.color);

    /* -- docstring, imports, and every constant this planet needs -- */
    L.push('#!/usr/bin/env python3');
    L.push('"""');
    L.push('ASCII ' + c.texture + ' planet, generated by cosmos.js.');
    L.push('');
    L.push('Standard library only. Run it and it animates in the terminal;');
    L.push('pass --once to print a single frame and exit.');
    L.push('"""');
    L.push('import math, sys, time');
    L.push('');
    L.push('RAMP = " .:-=+*#%@"');
    L.push('COLS, ROWS = ' + i(b.cols) + ', ' + i(b.rows));
    L.push('EXT_X, EXT_Y = ' + n(b.extX) + ', ' + n(b.extY) + '   # frame half-size, in body radii');
    L.push('TILT, ROLL = ' + n(c.tilt) + ', ' + n(c.roll));
    L.push('AMBIENT   = ' + n(c.ambient) + '   # light on the night side');
    L.push('GAIN      = ' + n(c.brightness));
    L.push('SPEED     = ' + n(c.speed * c.direction) + '   # radians per second');
    L.push('LIGHT     = (' + n(Cosmos.LIGHT[0]) + ', ' + n(Cosmos.LIGHT[1]) + ', ' + n(Cosmos.LIGHT[2]) + ')   # key light, upper left');
    if (p.rock) L.push('MAXR      = ' + n(b.max) + '   # bounding radius, measured not summed');
    if (p.rings) {
      L.push('RING_IN, RING_OUT = ' + n(c.ringInner) + ', ' + n(c.ringOuter));
      L.push('RING_GAPS = ((1.68, 1.78), (2.04, 2.09))');
    }
    L.push('COLOR     = (' + rgb.join(', ') + ')');
    L.push('');
    L.push('');
    /* -- the PRNG, shared by everything that scatters -- */
    L.push('def rng(seed):');
    L.push('    """Linear congruential generator, matching the JavaScript original');
    L.push('    exactly: the mask is what JavaScript\'s >>> 0 does for free."""');
    L.push('    s = seed & 0xFFFFFFFF');
    L.push('');
    L.push('    def nxt():');
    L.push('        nonlocal s');
    L.push('        s = (s * 1664525 + 1013904223) & 0xFFFFFFFF');
    L.push('        return s / 4294967296');
    L.push('');
    L.push('    return nxt');
    L.push('');
    L.push('');

    /* -- the scatter helpers, only the ones this planet calls -- */
    if (p.craters || p.maria) {
      L.push('def features(seed, count, r_min, r_span):');
      L.push('    """Surface blobs as unit vectors plus a cosine radius, so a lookup');
      L.push('    is a dot product instead of inverse trig for every glyph."""');
      L.push('    r = rng(seed)');
      L.push('    out = []');
      L.push('    for _ in range(count):');
      L.push('        y = r() * 2 - 1');
      L.push('        ph = r() * math.pi * 2');
      L.push('        s = math.sqrt(max(0.0, 1 - y * y))');
      L.push('        rad = r_min + r() * r_span');
      L.push('        out.append((s * math.cos(ph), y, s * math.sin(ph),');
      L.push('                    math.cos(rad), math.cos(rad * 0.7)))');
      L.push('    return out');
      L.push('');
      L.push('');
    }
    if (p.cracks) {
      L.push('def circles(seed, count, w_min, w_span):');
      L.push('    """A plane through the centre cuts the sphere in a great circle, so');
      L.push('    abs(dot(p, n)) is the distance from that line. Gives a feature that');
      L.push('    wraps the whole body, which no blob can do."""');
      L.push('    r = rng(seed)');
      L.push('    out = []');
      L.push('    for _ in range(count):');
      L.push('        y = r() * 2 - 1');
      L.push('        ph = r() * math.pi * 2');
      L.push('        s = math.sqrt(max(0.0, 1 - y * y))');
      L.push('        out.append((s * math.cos(ph), y, s * math.sin(ph),');
      L.push('                    w_min + r() * w_span))');
      L.push('    return out');
      L.push('');
      L.push('');
    }
    if (p.rock) {
      L.push('def lobes(seed, count, a_min, a_span, neg_chance):');
      L.push('    """Deformation lobes in BODY space. That is the whole point: rotating');
      L.push('    the body rotates the lumps, which is what makes an asteroid read as');
      L.push('    an asteroid rather than a sphere wearing a moving texture."""');
      L.push('    r = rng(seed)');
      L.push('    out = []');
      L.push('    for _ in range(count):');
      L.push('        y = r() * 2 - 1');
      L.push('        ph = r() * math.pi * 2');
      L.push('        c = math.sqrt(max(0.0, 1 - y * y))');
      L.push('        amp = (a_min + r() * a_span) * (-1 if r() < neg_chance else 1)');
      L.push('        out.append((c * math.cos(ph), y, c * math.sin(ph), amp))');
      L.push('    return out');
      L.push('');
      L.push('');
    }

    /* -- the feature tables themselves, built once at import -- */
    if (p.craters) L.push('CRATERS = features(' + s.craters + ', ' + i(c.craters) + ', 0.15, 0.20)');
    if (p.maria)   L.push('MARIA   = features(' + s.maria + ', 5, 0.40, 0.26)');
    if (p.cracks)  L.push('CRACKS  = circles(' + s.cracks + ', 8, 0.046, 0.042)');
    if (p.rock) {
      L.push('SHAPE   = lobes(' + s.shape + ', 5, ' + n(0.105 * c.lumpiness) + ', ' + n(0.075 * c.lumpiness) + ', 0.50)');
      L.push('FACETS  = lobes(' + s.facets + ', 14, ' + n(0.034 * c.lumpiness) + ', ' + n(0.042 * c.lumpiness) + ', 0.45)');
      L.push('KNOBS   = lobes(' + s.knobs + ', 24, ' + n(0.018 * c.lumpiness) + ', ' + n(0.036 * c.lumpiness) + ', 0.45)');
      L.push('ELONG   = ' + n(0.24 * c.lumpiness));
    }
    L.push('');
    L.push('');

    /* -- the albedo function for this one texture -- */
    L.push('def texture(bx, by, bz, la, lo):');
    L.push('    """Albedo at a point on the surface, around 1.0."""');
    L.push(texturePy(c.texture));
    L.push('');
    L.push('');

    /* -- the surface shape, for a lumpy body only -- */
    if (p.rock) {
      L.push('def radius(bx, by, bz):');
      L.push('    """Direction-varying radius. Powers are written out as products:');
      L.push('    pow() here would run a million times per frame."""');
      L.push('    r = 1.0 + ELONG * (bx * bx - 0.34)');
      L.push('    for lx, ly, lz, a in SHAPE:          # signed, gentle: the silhouette');
      L.push('        d = bx * lx + by * ly + bz * lz');
      L.push('        r += a * d * d * d');
      L.push('    for lx, ly, lz, a in FACETS:         # one-sided: flats and edges');
      L.push('        d = bx * lx + by * ly + bz * lz');
      L.push('        if d > 0:');
      L.push('            d2 = d * d');
      L.push('            r += a * d2 * d2 * d');
      L.push('    for lx, ly, lz, a in KNOBS:          # tight: knobs and pits');
      L.push('        d = bx * lx + by * ly + bz * lz');
      L.push('        if d > 0:');
      L.push('            d3 = d * d * d');
      L.push('            r += a * d3 * d3 * d3');
      L.push('    return r');
      L.push('');
      L.push('');
    }

    /* -- one frame: the same per-glyph loop as Cosmos.render -- */
    L.push('def frame(angle):');
    L.push('    """One frame, as a string of ROWS lines."""');
    L.push('    ct, st = math.cos(TILT), math.sin(TILT)');
    L.push('    nx, ny, nz = -math.sin(ROLL) * ct, math.cos(ROLL) * ct, st');
    L.push('');
    L.push('    # An orthonormal equatorial basis perpendicular to the axis.');
    L.push('    hx, hy, hz = (1.0, 0.0, 0.0) if abs(nz) > 0.9 else (0.0, 0.0, 1.0)');
    L.push('    ux, uy, uz = hy * nz - hz * ny, hz * nx - hx * nz, hx * ny - hy * nx');
    L.push('    um = math.sqrt(ux * ux + uy * uy + uz * uz) or 1.0');
    L.push('    ux, uy, uz = ux / um, uy / um, uz / um');
    L.push('    vx, vy, vz = ny * uz - nz * uy, nz * ux - nx * uz, nx * uy - ny * ux');
    L.push('');
    L.push('    ca, sa = math.cos(angle), math.sin(angle)');
    L.push('    lx, ly, lz = LIGHT');
    L.push('    last = len(RAMP) - 1');
    L.push('');
    L.push('    def to_body(px, py, pz):');
    L.push('        """View space to body space. Returns the distance from the centre');
    L.push('        along with the direction, since the caller needs both."""');
    L.push('        d = math.sqrt(px * px + py * py + pz * pz) or 1.0');
    L.push('        ax, ay, az = px / d, py / d, pz / d');
    L.push('        b1y = ax * nx + ay * ny + az * nz');
    L.push('        b0 = ax * ux + ay * uy + az * uz');
    L.push('        b1 = ax * vx + ay * vy + az * vz');
    L.push('        return d, b0 * ca + b1 * sa, b1y, b1 * ca - b0 * sa');
    L.push('');
    L.push('    rows = []');
    L.push('    for j in range(ROWS):');
    L.push('        line = []');
    L.push('        sy = (1 - 2 * (j + 0.5) / ROWS) * EXT_Y');
    L.push('        for k in range(COLS):');
    L.push('            sx = (2 * (k + 0.5) / COLS - 1) * EXT_X');
    L.push('            d2 = sx * sx + sy * sy');
    L.push('');
    L.push('            sphere, zs, hit = -1.0, -1e9, False');
    if (p.rock) {
      L.push('            # Bisect down the ray. Newton would take fewer steps but blows');
      L.push('            # up near the silhouette where the surface is edge-on.');
      L.push('            hi = MAXR * MAXR - d2');
      L.push('            if hi > 0:');
      L.push('                hi = math.sqrt(hi)');
      L.push('                lo = 0.0');
      L.push('                # Is the z=0 point already inside the body? to_body');
      L.push('                # hands back the distance as well as the direction, and');
      L.push('                # it is the distance that decides the silhouette.');
      L.push('                dd, bx, by, bz = to_body(sx, sy, 0.0)');
      L.push('                if dd < radius(bx, by, bz):');
      L.push('                    for _ in range(9):');
      L.push('                        mid = (lo + hi) * 0.5');
      L.push('                        dd, bx, by, bz = to_body(sx, sy, mid)');
      L.push('                        if dd < radius(bx, by, bz):');
      L.push('                            lo = mid');
      L.push('                        else:');
      L.push('                            hi = mid');
      L.push('                    zs, hit = lo, True');
    } else {
      L.push('            if d2 <= 1:');
      L.push('                zs, hit = math.sqrt(1 - d2), True');
    }
    L.push('');
    L.push('            if hit:');
    L.push('                lp, bx, by, bz = to_body(sx, sy, zs)');
    L.push('                nzv = zs / lp                     # cosine of the view angle');
    L.push('                lum = (sx / lp) * lx + (sy / lp) * ly + nzv * lz');
    L.push('                if lum < 0:');
    L.push('                    lum = 0.0');
    L.push('                byc = min(1.0, max(-1.0, by))');
    L.push('                alb = texture(bx, byc, bz, math.asin(byc), math.atan2(bz, bx))');
    L.push('                sphere = alb * (AMBIENT + (1 - AMBIENT) * lum * (0.45 + 0.55 * lum))');
    L.push('                sphere *= (0.58 + 0.42 * nzv) * GAIN      # limb darkening');
    L.push('');
    L.push('            ring_lum, cov, zr = 0.0, 0.0, -1e9');
    if (p.rings) {
      L.push('            # The rings are a translucent sheet, not a surface: a faint');
      L.push('            # band in front of the planet composites over it.');
      L.push('            if abs(nz) > 0.05:');
      L.push('                zr = -(nx * sx + ny * sy) / nz');
      L.push('                rr = math.sqrt(d2 + zr * zr)');
      L.push('                if RING_IN <= rr <= RING_OUT and not any(a < rr < b for a, b in RING_GAPS):');
      L.push('                    t = (rr - RING_IN) / (RING_OUT - RING_IN)');
      L.push('                    cov = (0.55 + 0.45 * math.sin(t * 8.2)) * (1 - 0.45 * t)');
      L.push('                    # Inner material shears ahead of outer on a Keplerian');
      L.push('                    # profile. Without it the rings are radially symmetric');
      L.push('                    # and look frozen at every angle.');
      L.push('                    au = sx * ux + sy * uy + zr * uz');
      L.push('                    av = sx * vx + sy * vy + zr * vz');
      L.push('                    phi = math.atan2(av, au) - angle * (rr ** -1.5) * 1.7');
      L.push('                    cov *= 0.70 + 0.30 * (0.62 * math.sin(phi * 2.0 + 0.4)');
      L.push('                                        + 0.38 * math.sin(phi * 5.0 - 1.1))');
      L.push('                    cov = min(1.0, max(0.0, cov)) * (0.55 + 0.45 * (1 - abs(nz)))');
      L.push('                    ring_lum = 0.88 * GAIN');
      L.push('                    ql = sx * lx + sy * ly + zr * lz     # planet shadow');
      L.push('                    if ql < 0:');
      L.push('                        px, py, pz = sx - ql * lx, sy - ql * ly, zr - ql * lz');
      L.push('                        if px * px + py * py + pz * pz < 1:');
      L.push('                            ring_lum *= 0.16');
    }
    L.push('');
    L.push('            back = sphere if sphere >= 0 else 0.0');
    L.push('            if cov > 0 and (d2 > 1 or zr > zs):');
    L.push('                v = ring_lum * cov + back * (1 - cov)');
    L.push('            else:');
    L.push('                v = back');
    L.push('            # int(x + 0.5), not round(): Python rounds half to even and');
    L.push('            # would pick a different glyph than the JavaScript original.');
    L.push('            line.append(RAMP[int(min(1.0, max(0.0, v)) * last + 0.5)])');
    L.push('        rows.append("".join(line))');
    L.push('    return "\\n".join(rows)');
    L.push('');
    L.push('');
    /* -- driver: animates in the terminal, or --once for a still -- */
    L.push('def main():');
    L.push('    tint = "\\x1b[38;2;%d;%d;%dm" % COLOR');
    L.push('    if "--once" in sys.argv:');
    L.push('        print(tint + frame(0.0) + "\\x1b[0m")');
    L.push('        return');
    L.push('    start = time.time()');
    L.push('    try:');
    L.push('        sys.stdout.write("\\x1b[?25l")            # hide the cursor');
    L.push('        while True:');
    L.push('            angle = (time.time() - start) * SPEED');
    L.push('            sys.stdout.write("\\x1b[H" + tint + frame(angle) + "\\x1b[0m")');
    L.push('            sys.stdout.flush()');
    L.push('            time.sleep(1 / 30)');
    L.push('    except KeyboardInterrupt:');
    L.push('        pass');
    L.push('    finally:');
    L.push('        sys.stdout.write("\\x1b[?25h\\x1b[0m\\n")  # restore it');
    L.push('');
    L.push('');
    L.push('if __name__ == "__main__":');
    L.push('    main()');
    return L.join('\n') + '\n';
  }

  /* The albedo functions from planet.js, hand-ported to Python, as a block of
     indented lines ready to drop inside `def texture(...)`.

     These have to stay in step with TEXTURES over there. Nothing checks, and
     a drift shows up only as an export that draws a slightly different planet
     from the one on the screen beside it.

     Note the fall-through: an unknown texture emits rock, where planet.js
     build() falls back to cratered. Neither is reachable from the UI, which
     only ever offers the six that exist. */
  function texturePy(kind) {
    if (kind === 'cratered') return [
      '    a = 0.86',
      '    for cx, cy, cz, cc, rim in MARIA:',
      '        d = bx * cx + by * cy + bz * cz',
      '        if d > cc:',
      '            a -= 0.40 * (d - cc) / (1 - cc)',
      '    for cx, cy, cz, cc, rim in CRATERS:',
      '        d = bx * cx + by * cy + bz * cz',
      '        if d > cc:',
      '            a += 0.22 if d < rim else -0.26   # bright rim, dark floor',
      '    return min(1.12, max(0.12, a))'
    ].join('\n');
    if (kind === 'ice') return [
      '    a = 1.00',
      '    for cx, cy, cz, cc, rim in MARIA:              # chaos terrain',
      '        d = bx * cx + by * cy + bz * cz',
      '        if d > cc:',
      '            a -= 0.16 * (d - cc) / (1 - cc)',
      '    for cx, cy, cz, w in CRACKS:                   # fractures',
      '        d = abs(bx * cx + by * cy + bz * cz)',
      '        if d < w:',
      '            a -= 0.60 * (1 - 0.45 * d / w)',
      '        elif d < w * 1.8:',
      '            a += 0.14 * (1 - (d - w) / (w * 0.8))',
      '    for cx, cy, cz, cc, rim in CRATERS:            # fresh impacts',
      '        d = bx * cx + by * cy + bz * cz',
      '        if d > cc:',
      '            a += 0.26 * (d - cc) / (1 - cc)',
      '    a += 0.03 * math.sin(lo * 8.0 + la * 5.0)',
      '    return min(1.22, max(0.10, a))'
    ].join('\n');
    if (kind === 'gas') return [
      '    # Latitude bands alone are rotation-invariant: the body would turn and',
      '    # look completely still. The longitude terms make the spin legible.',
      '    a = (0.80 + 0.17 * math.sin(la * 12.5)',
      '              + 0.10 * math.sin(la * 5.5 + 0.8)',
      '              + 0.14 * math.sin(lo * 4.0 + la * 14.0)    # festoons',
      '              + 0.07 * math.sin(lo * 7.0 - la * 9.0))    # turbulence',
      '    dl = ((lo - 0.7 + math.pi) % (2 * math.pi) - math.pi) * 0.62',
      '    dla = (la + 0.33) * 1.9',
      '    d = math.sqrt(dl * dl + dla * dla)                   # the storm',
      '    if d < 0.42:',
      '        a *= 0.50 + 0.36 * (d / 0.42)',
      '    return min(1.15, max(0.12, a))'
    ].join('\n');
    if (kind === 'desert') return [
      '    a = (0.78 + 0.09 * math.sin(lo * 3.4 + la * 2.1)',
      '              + 0.06 * math.sin(la * 6.3 - lo * 1.7))',
      '    for cx, cy, cz, cc, rim in MARIA:',
      '        d = bx * cx + by * cy + bz * cz',
      '        if d > cc:',
      '            a -= 0.24 * (d - cc) / (1 - cc)',
      '    p = abs(la)                                    # polar caps',
      '    if p > 1.16:',
      '        a = 1.20',
      '    elif p > 0.99:',
      '        a += 0.42 * (p - 0.99) / 0.17',
      '    return min(1.20, max(0.15, a))'
    ].join('\n');
    if (kind === 'lava') return [
      '    a = 0.26',
      '    for cx, cy, cz, w in CRACKS:                   # glowing fissures',
      '        d = abs(bx * cx + by * cy + bz * cz)',
      '        if d < w * 2.4:',
      '            a += 0.90 * (1 - d / (w * 2.4))',
      '    for cx, cy, cz, cc, rim in CRATERS:            # hot pools',
      '        d = bx * cx + by * cy + bz * cz',
      '        if d > cc:',
      '            a += 0.55 * (d - cc) / (1 - cc)',
      '    a += 0.05 * math.sin(lo * 9.0 + la * 6.0)',
      '    return min(1.30, max(0.05, a))'
    ].join('\n');
    return [
      '    a = (0.72 + 0.10 * math.sin(lo * 6.0 + la * 4.0)',
      '              + 0.06 * math.sin(lo * 13.0 - la * 7.0))',
      '    for cx, cy, cz, cc, rim in CRATERS:',
      '        d = bx * cx + by * cy + bz * cz',
      '        if d > cc:',
      '            a += 0.16 if d < rim else -0.20',
      '    return min(1.10, max(0.10, a))'
    ].join('\n');
  }

  /* ---------------------------------------------------------- *
     JavaScript
     ---------------------------------------------------------- */
  /* Same contract as python() above, and deliberately the same shape: the two
     read down the page in step, so a change to one is easy to mirror in the
     other. */
  function javascript(c, b) {
    var s = seeds(c), p = parts(c), L = [];

    /* -- header comment, and every constant this planet needs -- */
    L.push('/* ASCII ' + c.texture + ' planet, generated by cosmos.js.');
    L.push('');
    L.push('   Self-contained: no imports, no dependencies. In a browser, point it');
    L.push('   at a <pre> and call animate(). Under Node, call frame(0) and print.');
    L.push('*/');
    L.push('var RAMP = " .:-=+*#%@";');
    L.push('var COLS = ' + i(b.cols) + ', ROWS = ' + i(b.rows) + ';');
    L.push('var EXT_X = ' + n(b.extX) + ', EXT_Y = ' + n(b.extY) + ';   // frame half-size, in body radii');
    L.push('var TILT = ' + n(c.tilt) + ', ROLL = ' + n(c.roll) + ';');
    L.push('var AMBIENT = ' + n(c.ambient) + ';        // light on the night side');
    L.push('var GAIN = ' + n(c.brightness) + ';');
    L.push('var SPEED = ' + n(c.speed * c.direction) + ';          // radians per second');
    L.push('var LIGHT = [' + n(Cosmos.LIGHT[0]) + ', ' + n(Cosmos.LIGHT[1]) + ', ' + n(Cosmos.LIGHT[2]) + '];  // key light, upper left');
    if (p.rock) L.push('var MAXR = ' + n(b.max) + ';           // bounding radius, measured not summed');
    if (p.rings) {
      L.push('var RING_IN = ' + n(c.ringInner) + ', RING_OUT = ' + n(c.ringOuter) + ';');
      L.push('var RING_GAPS = [[1.68, 1.78], [2.04, 2.09]];');
    }
    L.push('var COLOR = "' + c.color + '";');
    L.push('');
    /* -- the PRNG, shared by everything that scatters -- */
    L.push('/* Linear congruential generator: same seed, same craters, every run. */');
    L.push('function rng(seed) {');
    L.push('  var s = seed >>> 0;');
    L.push('  return function () {');
    L.push('    s = (s * 1664525 + 1013904223) >>> 0;');
    L.push('    return s / 4294967296;');
    L.push('  };');
    L.push('}');
    L.push('');

    /* -- the scatter helpers, only the ones this planet calls -- */
    if (p.craters || p.maria) {
      L.push('/* Surface blobs as unit vectors plus a cosine radius, so a lookup is a');
      L.push('   dot product instead of inverse trig for every glyph. */');
      L.push('function features(seed, count, rMin, rSpan) {');
      L.push('  var r = rng(seed), out = [];');
      L.push('  for (var i = 0; i < count; i++) {');
      L.push('    var y = r() * 2 - 1, ph = r() * Math.PI * 2;');
      L.push('    var s = Math.sqrt(Math.max(0, 1 - y * y)), rad = rMin + r() * rSpan;');
      L.push('    out.push([s * Math.cos(ph), y, s * Math.sin(ph),');
      L.push('              Math.cos(rad), Math.cos(rad * 0.7)]);');
      L.push('  }');
      L.push('  return out;');
      L.push('}');
      L.push('');
    }
    if (p.cracks) {
      L.push('/* A plane through the centre cuts the sphere in a great circle, so');
      L.push('   abs(dot(p, n)) is the distance from that line. */');
      L.push('function circles(seed, count, wMin, wSpan) {');
      L.push('  var r = rng(seed), out = [];');
      L.push('  for (var i = 0; i < count; i++) {');
      L.push('    var y = r() * 2 - 1, ph = r() * Math.PI * 2;');
      L.push('    var s = Math.sqrt(Math.max(0, 1 - y * y));');
      L.push('    out.push([s * Math.cos(ph), y, s * Math.sin(ph), wMin + r() * wSpan]);');
      L.push('  }');
      L.push('  return out;');
      L.push('}');
      L.push('');
    }
    if (p.rock) {
      L.push('/* Deformation lobes in BODY space: rotating the body rotates the lumps,');
      L.push('   which is what makes an asteroid read as one. */');
      L.push('function lobes(seed, count, aMin, aSpan, negChance) {');
      L.push('  var r = rng(seed), out = [];');
      L.push('  for (var i = 0; i < count; i++) {');
      L.push('    var y = r() * 2 - 1, ph = r() * Math.PI * 2;');
      L.push('    var c = Math.sqrt(Math.max(0, 1 - y * y));');
      L.push('    out.push([c * Math.cos(ph), y, c * Math.sin(ph),');
      L.push('              (aMin + r() * aSpan) * (r() < negChance ? -1 : 1)]);');
      L.push('  }');
      L.push('  return out;');
      L.push('}');
      L.push('');
    }

    /* -- the feature tables themselves, built once at load -- */
    if (p.craters) L.push('var CRATERS = features(' + s.craters + ', ' + i(c.craters) + ', 0.15, 0.20);');
    if (p.maria)   L.push('var MARIA = features(' + s.maria + ', 5, 0.40, 0.26);');
    if (p.cracks)  L.push('var CRACKS = circles(' + s.cracks + ', 8, 0.046, 0.042);');
    if (p.rock) {
      L.push('var SHAPE = lobes(' + s.shape + ', 5, ' + n(0.105 * c.lumpiness) + ', ' + n(0.075 * c.lumpiness) + ', 0.50);');
      L.push('var FACETS = lobes(' + s.facets + ', 14, ' + n(0.034 * c.lumpiness) + ', ' + n(0.042 * c.lumpiness) + ', 0.45);');
      L.push('var KNOBS = lobes(' + s.knobs + ', 24, ' + n(0.018 * c.lumpiness) + ', ' + n(0.036 * c.lumpiness) + ', 0.45);');
      L.push('var ELONG = ' + n(0.24 * c.lumpiness) + ';');
    }
    L.push('');
    /* -- the albedo function for this one texture -- */
    L.push('/* Albedo at a point on the surface, around 1.0. */');
    L.push('function texture(bx, by, bz, la, lo) {');
    L.push(textureJs(c.texture));
    L.push('}');
    L.push('');

    /* -- the surface shape, for a lumpy body only -- */
    if (p.rock) {
      L.push('/* Direction-varying radius. Powers are written as products: Math.pow');
      L.push('   here would run a million times per frame. */');
      L.push('function radius(bx, by, bz) {');
      L.push('  var r = 1 + ELONG * (bx * bx - 0.34), i, L, d, d2, d3;');
      L.push('  for (i = 0; i < SHAPE.length; i++) {        // signed: the silhouette');
      L.push('    L = SHAPE[i]; d = bx * L[0] + by * L[1] + bz * L[2];');
      L.push('    r += L[3] * d * d * d;');
      L.push('  }');
      L.push('  for (i = 0; i < FACETS.length; i++) {       // one-sided: flats');
      L.push('    L = FACETS[i]; d = bx * L[0] + by * L[1] + bz * L[2];');
      L.push('    if (d > 0) { d2 = d * d; r += L[3] * d2 * d2 * d; }');
      L.push('  }');
      L.push('  for (i = 0; i < KNOBS.length; i++) {        // tight: knobs and pits');
      L.push('    L = KNOBS[i]; d = bx * L[0] + by * L[1] + bz * L[2];');
      L.push('    if (d > 0) { d3 = d * d * d; r += L[3] * d3 * d3 * d3; }');
      L.push('  }');
      L.push('  return r;');
      L.push('}');
      L.push('');
    }

    /* -- one frame: the same per-glyph loop as Cosmos.render -- */
    L.push('/* One frame, as a string of ROWS lines. */');
    L.push('function frame(angle) {');
    L.push('  var ct = Math.cos(TILT), st = Math.sin(TILT);');
    L.push('  var nx = -Math.sin(ROLL) * ct, ny = Math.cos(ROLL) * ct, nz = st;');
    L.push('');
    L.push('  // An orthonormal equatorial basis perpendicular to the axis.');
    L.push('  var hx = 0, hy = 0, hz = 1;');
    L.push('  if (Math.abs(nz) > 0.9) { hx = 1; hz = 0; }');
    L.push('  var ux = hy * nz - hz * ny, uy = hz * nx - hx * nz, uz = hx * ny - hy * nx;');
    L.push('  var um = Math.sqrt(ux * ux + uy * uy + uz * uz) || 1;');
    L.push('  ux /= um; uy /= um; uz /= um;');
    L.push('  var vx = ny * uz - nz * uy, vy = nz * ux - nx * uz, vz = nx * uy - ny * ux;');
    L.push('');
    L.push('  var ca = Math.cos(angle), sa = Math.sin(angle);');
    L.push('  var lx = LIGHT[0], ly = LIGHT[1], lz = LIGHT[2];');
    L.push('  var last = RAMP.length - 1;');
    L.push('');
    L.push('  // Scratch rather than a returned array: this runs once per bisection');
    L.push('  // step per cell, and allocating there would be all GC and no work.');
    L.push('  var _bx = 0, _by = 0, _bz = 0;');
    L.push('  function toBody(px, py, pz) {');
    L.push('    var d = Math.sqrt(px * px + py * py + pz * pz) || 1;');
    L.push('    var ax = px / d, ay = py / d, az = pz / d;');
    L.push('    _by = ax * nx + ay * ny + az * nz;');
    L.push('    var b0 = ax * ux + ay * uy + az * uz;');
    L.push('    var b1 = ax * vx + ay * vy + az * vz;');
    L.push('    _bx = b0 * ca + b1 * sa;');
    L.push('    _bz = b1 * ca - b0 * sa;');
    L.push('    return d;');
    L.push('  }');
    L.push('');
    L.push('  var out = [];');
    L.push('  for (var j = 0; j < ROWS; j++) {');
    L.push('    var line = [];');
    L.push('    var sy = (1 - 2 * (j + 0.5) / ROWS) * EXT_Y;');
    L.push('    for (var k = 0; k < COLS; k++) {');
    L.push('      var sx = (2 * (k + 0.5) / COLS - 1) * EXT_X;');
    L.push('      var d2 = sx * sx + sy * sy;');
    L.push('      var sphere = -1, zs = -1e9, hit = false;');
    if (p.rock) {
      L.push('');
      L.push('      // Bisect down the ray. Newton would take fewer steps but blows up');
      L.push('      // near the silhouette where the surface is edge-on.');
      L.push('      var hi = MAXR * MAXR - d2;');
      L.push('      if (hi > 0) {');
      L.push('        hi = Math.sqrt(hi);');
      L.push('        var lo = 0;');
      L.push('        if (toBody(sx, sy, 0) < radius(_bx, _by, _bz)) {');
      L.push('          for (var q = 0; q < 9; q++) {');
      L.push('            var mid = (lo + hi) * 0.5;');
      L.push('            if (toBody(sx, sy, mid) < radius(_bx, _by, _bz)) lo = mid;');
      L.push('            else hi = mid;');
      L.push('          }');
      L.push('          zs = lo; hit = true;');
      L.push('        }');
      L.push('      }');
    } else {
      L.push('      if (d2 <= 1) { zs = Math.sqrt(1 - d2); hit = true; }');
    }
    L.push('');
    L.push('      if (hit) {');
    L.push('        var lp = toBody(sx, sy, zs);');
    L.push('        var nzv = zs / lp;                  // cosine of the view angle');
    L.push('        var lum = (sx / lp) * lx + (sy / lp) * ly + nzv * lz;');
    L.push('        if (lum < 0) lum = 0;');
    L.push('        var by = Math.min(1, Math.max(-1, _by));');
    L.push('        var alb = texture(_bx, by, _bz, Math.asin(by), Math.atan2(_bz, _bx));');
    L.push('        sphere = alb * (AMBIENT + (1 - AMBIENT) * lum * (0.45 + 0.55 * lum));');
    L.push('        sphere *= (0.58 + 0.42 * nzv) * GAIN;   // limb darkening');
    L.push('      }');
    L.push('');
    L.push('      var ringLum = 0, cov = 0, zr = -1e9;');
    if (p.rings) {
      L.push('      // The rings are a translucent sheet, not a surface: a faint band in');
      L.push('      // front of the planet composites over it rather than replacing it.');
      L.push('      if (Math.abs(nz) > 0.05) {');
      L.push('        zr = -(nx * sx + ny * sy) / nz;');
      L.push('        var rr = Math.sqrt(d2 + zr * zr);');
      L.push('        if (rr >= RING_IN && rr <= RING_OUT) {');
      L.push('          var open = true;');
      L.push('          for (var g = 0; g < RING_GAPS.length; g++) {');
      L.push('            if (rr > RING_GAPS[g][0] && rr < RING_GAPS[g][1]) { open = false; break; }');
      L.push('          }');
      L.push('          if (open) {');
      L.push('            var t = (rr - RING_IN) / (RING_OUT - RING_IN);');
      L.push('            cov = (0.55 + 0.45 * Math.sin(t * 8.2)) * (1 - 0.45 * t);');
      L.push('            // Inner material shears ahead of outer on a Keplerian profile.');
      L.push('            // Without it the rings look frozen at every angle.');
      L.push('            var au = sx * ux + sy * uy + zr * uz;');
      L.push('            var av = sx * vx + sy * vy + zr * vz;');
      L.push('            var phi = Math.atan2(av, au) - angle * Math.pow(rr, -1.5) * 1.7;');
      L.push('            cov *= 0.70 + 0.30 * (0.62 * Math.sin(phi * 2.0 + 0.4)');
      L.push('                                + 0.38 * Math.sin(phi * 5.0 - 1.1));');
      L.push('            cov = Math.min(1, Math.max(0, cov)) * (0.55 + 0.45 * (1 - Math.abs(nz)));');
      L.push('            ringLum = 0.88 * GAIN;');
      L.push('            var ql = sx * lx + sy * ly + zr * lz;    // planet shadow');
      L.push('            if (ql < 0) {');
      L.push('              var px = sx - ql * lx, py = sy - ql * ly, pz = zr - ql * lz;');
      L.push('              if (px * px + py * py + pz * pz < 1) ringLum *= 0.16;');
      L.push('            }');
      L.push('          }');
      L.push('        }');
      L.push('      }');
    }
    L.push('');
    L.push('      var back = sphere >= 0 ? sphere : 0;');
    L.push('      var v = (cov > 0 && (d2 > 1 || zr > zs))');
    L.push('            ? ringLum * cov + back * (1 - cov)');
    L.push('            : back;');
    L.push('      line.push(RAMP.charAt(Math.round(Math.min(1, Math.max(0, v)) * last)));');
    L.push('    }');
    L.push('    out.push(line.join(""));');
    L.push('  }');
    L.push('  return out.join("\\n");');
    L.push('}');
    L.push('');
    /* -- driver: animates in a browser, prints one frame under Node -- */
    L.push('/* Browser driver. Give it a <pre> and it runs on wall-clock time. */');
    L.push('function animate(el) {');
    L.push('  el.style.font = "12px/1 ui-monospace, monospace";');
    L.push('  el.style.color = COLOR;');
    L.push('  el.style.whiteSpace = "pre";');
    L.push('  var t0 = performance.now();');
    L.push('  (function tick(now) {');
    L.push('    el.textContent = frame((now - t0) / 1000 * SPEED);');
    L.push('    requestAnimationFrame(tick);');
    L.push('  })(t0);');
    L.push('}');
    L.push('');
    L.push('if (typeof document !== "undefined") {');
    L.push('  var host = document.createElement("pre");');
    L.push('  document.body.appendChild(host);');
    L.push('  animate(host);');
    L.push('} else if (typeof console !== "undefined") {');
    L.push('  console.log(frame(0));           // Node: one frame to stdout');
    L.push('}');
    return L.join('\n') + '\n';
  }

  /* The same six again in JavaScript. Same warning as texturePy: this is a
     hand-kept copy of TEXTURES in planet.js, not a translation of it. */
  function textureJs(kind) {
    if (kind === 'cratered') return [
      '  var a = 0.86, i, c, d;',
      '  for (i = 0; i < MARIA.length; i++) {',
      '    c = MARIA[i]; d = bx * c[0] + by * c[1] + bz * c[2];',
      '    if (d > c[3]) a -= 0.40 * (d - c[3]) / (1 - c[3]);',
      '  }',
      '  for (i = 0; i < CRATERS.length; i++) {',
      '    c = CRATERS[i]; d = bx * c[0] + by * c[1] + bz * c[2];',
      '    if (d > c[3]) a += (d < c[4]) ? 0.22 : -0.26;   // bright rim, dark floor',
      '  }',
      '  return Math.min(1.12, Math.max(0.12, a));'
    ].join('\n');
    if (kind === 'ice') return [
      '  var a = 1.00, i, c, d;',
      '  for (i = 0; i < MARIA.length; i++) {              // chaos terrain',
      '    c = MARIA[i]; d = bx * c[0] + by * c[1] + bz * c[2];',
      '    if (d > c[3]) a -= 0.16 * (d - c[3]) / (1 - c[3]);',
      '  }',
      '  for (i = 0; i < CRACKS.length; i++) {             // fractures',
      '    c = CRACKS[i]; d = Math.abs(bx * c[0] + by * c[1] + bz * c[2]);',
      '    if (d < c[3]) a -= 0.60 * (1 - 0.45 * d / c[3]);',
      '    else if (d < c[3] * 1.8) a += 0.14 * (1 - (d - c[3]) / (c[3] * 0.8));',
      '  }',
      '  for (i = 0; i < CRATERS.length; i++) {            // fresh impacts',
      '    c = CRATERS[i]; d = bx * c[0] + by * c[1] + bz * c[2];',
      '    if (d > c[3]) a += 0.26 * (d - c[3]) / (1 - c[3]);',
      '  }',
      '  a += 0.03 * Math.sin(lo * 8.0 + la * 5.0);',
      '  return Math.min(1.22, Math.max(0.10, a));'
    ].join('\n');
    if (kind === 'gas') return [
      '  // Latitude bands alone are rotation-invariant: the body would turn and',
      '  // look completely still. The longitude terms make the spin legible.',
      '  var a = 0.80 + 0.17 * Math.sin(la * 12.5)',
      '               + 0.10 * Math.sin(la * 5.5 + 0.8)',
      '               + 0.14 * Math.sin(lo * 4.0 + la * 14.0)    // festoons',
      '               + 0.07 * Math.sin(lo * 7.0 - la * 9.0);    // turbulence',
      '  var w = lo - 0.7;',
      '  while (w > Math.PI) w -= 2 * Math.PI;',
      '  while (w < -Math.PI) w += 2 * Math.PI;',
      '  var dl = w * 0.62, dla = (la + 0.33) * 1.9;',
      '  var d = Math.sqrt(dl * dl + dla * dla);                 // the storm',
      '  if (d < 0.42) a *= 0.50 + 0.36 * (d / 0.42);',
      '  return Math.min(1.15, Math.max(0.12, a));'
    ].join('\n');
    if (kind === 'desert') return [
      '  var a = 0.78 + 0.09 * Math.sin(lo * 3.4 + la * 2.1)',
      '               + 0.06 * Math.sin(la * 6.3 - lo * 1.7);',
      '  for (var i = 0; i < MARIA.length; i++) {',
      '    var c = MARIA[i], d = bx * c[0] + by * c[1] + bz * c[2];',
      '    if (d > c[3]) a -= 0.24 * (d - c[3]) / (1 - c[3]);',
      '  }',
      '  var p = Math.abs(la);                            // polar caps',
      '  if (p > 1.16) a = 1.20;',
      '  else if (p > 0.99) a += 0.42 * (p - 0.99) / 0.17;',
      '  return Math.min(1.20, Math.max(0.15, a));'
    ].join('\n');
    if (kind === 'lava') return [
      '  var a = 0.26, i, c, d;',
      '  for (i = 0; i < CRACKS.length; i++) {             // glowing fissures',
      '    c = CRACKS[i]; d = Math.abs(bx * c[0] + by * c[1] + bz * c[2]);',
      '    if (d < c[3] * 2.4) a += 0.90 * (1 - d / (c[3] * 2.4));',
      '  }',
      '  for (i = 0; i < CRATERS.length; i++) {            // hot pools',
      '    c = CRATERS[i]; d = bx * c[0] + by * c[1] + bz * c[2];',
      '    if (d > c[3]) a += 0.55 * (d - c[3]) / (1 - c[3]);',
      '  }',
      '  a += 0.05 * Math.sin(lo * 9.0 + la * 6.0);',
      '  return Math.min(1.30, Math.max(0.05, a));'
    ].join('\n');
    return [
      '  var a = 0.72 + 0.10 * Math.sin(lo * 6.0 + la * 4.0)',
      '               + 0.06 * Math.sin(lo * 13.0 - la * 7.0);',
      '  for (var i = 0; i < CRATERS.length; i++) {',
      '    var c = CRATERS[i], d = bx * c[0] + by * c[1] + bz * c[2];',
      '    if (d > c[3]) a += (d < c[4]) ? 0.16 : -0.20;',
      '  }',
      '  return Math.min(1.10, Math.max(0.10, a));'
    ].join('\n');
  }

  /* "#rrggbb" -> [r, g, b]. Only the Python export wants this: it tints its
     output with an ANSI truecolor escape, which takes three numbers, where the
     JavaScript export hands the hex straight to CSS. */
  function hexToRgb(hex) {
    var h = hex.replace('#', '');
    return [parseInt(h.slice(0, 2), 16), parseInt(h.slice(2, 4), 16), parseInt(h.slice(4, 6), 16)];
  }

  /* Both take (cfg, body) and return a complete program as a string. */
  return { python: python, javascript: javascript };
})();
