#!/usr/bin/env python3
"""
Generates the static pages for msaunders.dev from a shared shell.

This is a convenience script, not a deploy step: it writes plain .html files
that are committed to the repo and served as-is by Cloudflare Pages.
Run it after editing NAV/FOOT or any page body below:

    python3 tools/build_pages.py
"""
import hashlib, os, re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
TABS = [("About", "/"), ("Misc", "/misc/")]

# Misc is finished enough to build but not to show, so /misc/ serves the holding
# screen instead and carries noindex. The real body is still MISC below and is
# still the thing this script would emit: flip this to True and rebuild to
# publish it (and put /misc/ back in sitemap.xml).
MISC_LIVE = False

SOCIAL_SVG = {}
with open(os.path.join(ROOT, "index.html"), encoding="utf-8") as f:
    _idx = f.read()
FOOT = re.search(r'<footer class="foot">.*?</footer>', _idx, re.S).group(0)


def crumb(trail):
    """Top-of-page breadcrumb. With the nav bar gone this is the only way back
    to the root from a sub-page, so every generated page carries one."""
    parts = ['<a href="/">msaunders.dev</a>']
    for label, href in trail:
        parts.append('<span class="crumb__sep">/</span>')
        parts.append('<a href="{}">{}</a>'.format(href, label) if href else "<span>{}</span>".format(label))
    return ('  <div class="wrap">\n'
            '    <nav class="crumb" aria-label="Breadcrumb">\n      '
            + "".join(parts)
            + '\n    </nav>\n  </div>')


ASSETS = ("css/site.css", "js/site.js", "js/cosmos.js",
          "favicon.svg", "favicon.png")


def stamp_assets():
    """Append a content hash to every CSS/JS URL in every page.

    Without a version in the URL, a browser that cached an asset under the old
    long max-age keeps serving it against freshly deployed HTML until its TTL
    expires. Changing the header alone cannot evict what is already cached, but
    changing the URL can, so the hash is what actually rescues a stale visitor.
    """
    vers = {}
    for a in ASSETS:
        with open(os.path.join(ROOT, a), "rb") as fh:
            vers[a] = hashlib.md5(fh.read()).hexdigest()[:8]

    pat = re.compile(
        r'(?P<attr>href|src)="/(?P<path>' + "|".join(a.replace(".", r"\.") for a in ASSETS)
        + r')(?:\?v=[0-9a-f]+)?"')

    def sub(m):
        return '{}="/{}?v={}"'.format(m.group("attr"), m.group("path"), vers[m.group("path")])

    touched = 0
    for root, _dirs, files in os.walk(ROOT):
        if os.sep + ".git" in root or os.sep + "assets" in root:
            continue
        for f in files:
            if not f.endswith(".html"):
                continue
            full = os.path.join(root, f)
            with open(full, encoding="utf-8") as fh:
                before = fh.read()
            after = pat.sub(sub, before)
            if after != before:
                with open(full, "w", encoding="utf-8") as fh:
                    fh.write(after)
                touched += 1
    print("  stamped {} page(s): {}".format(
        touched, "  ".join("{}={}".format(a.split("/")[-1], v) for a, v in vers.items())))


def page(path, *, title, desc, body, canonical, trail=(), noindex=False):
    html = f'''<!-- Generated by tools/build_pages.py. Do not hand-edit: edit the
     matching body constant in that script and re-run it. index.html is the
     exception, it is written by hand and only has its asset URLs stamped. -->
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title}</title>
<meta name="description" content="{desc}">
<meta name="theme-color" content="#000000">
{'<meta name="robots" content="noindex">' if noindex else f'<link rel="canonical" href="{canonical}">'}
<link rel="icon" href="/favicon.svg" type="image/svg+xml">
<link rel="alternate icon" href="/favicon.png">
<meta property="og:type" content="website">
<meta property="og:url" content="{canonical}">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<link rel="stylesheet" href="/css/site.css">
</head>
<body>
<a class="skip" href="#main">Skip to content</a>

<main id="main">
{crumb(trail) if trail else ""}
{body}
</main>

{FOOT}

<script src="/js/cosmos.js" defer></script>
<script src="/js/site.js" defer></script>
</body>
</html>
'''
    full = os.path.join(ROOT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(html)
    print(f"  {path:36s} {len(html):>7,} bytes")


# ==================================================================
#  PROJECTS / index
# ==================================================================
#  PROJECTS / GoDash
# ==================================================================
#  PROJECTS / Observatory (slot 02)
# ==================================================================
#  MISC  (hobbies + gallery, one page)
# ==============================================================
MISC = """
  <section class="hero">
    <div class="wrap">
      <p class="eyebrow"><b>//</b> Off the clock</p>
      <h1 class="h-xl">Misc</h1>
      <p class="lede">
        What I do when I am not writing code or studying, and the pictures that
        come out of it. Most of it feeds back into what I build.
      </p>
    </div>
  </section>

  <section class="section">
    <div class="wrap">
      <div class="empty">
        <div class="empty__icon">&hellip;</div>
        <h2>Section under construction</h2>
        <p>
          This page is reserved. The slots below are marked out.
        </p>
      </div>

      <div class="cols-3" style="margin-top:30px">
        <div class="card"><span class="card__idx">[ 01 ]</span><h2 class="card__title h-md">Astrophotography</h2><p class="card__body">Deep-sky imaging, long exposures, and the gear behind them.</p><span class="status status--soon"><i class="dot"></i>Pending</span></div>
        <div class="card"><span class="card__idx">[ 02 ]</span><h2 class="card__title h-md">Aerospace</h2><p class="card__body">Launches, orbital mechanics, and the programs pushing the boundary.</p><span class="status status--soon"><i class="dot"></i>Pending</span></div>
        <div class="card"><span class="card__idx">[ 03 ]</span><h2 class="card__title h-md">Computer building</h2><p class="card__body">Custom systems, thermals, and the newest silicon.</p><span class="status status--soon"><i class="dot"></i>Pending</span></div>
        <div class="card"><span class="card__idx">[ 04 ]</span><h2 class="card__title h-md">Camping &amp; hiking</h2><p class="card__body">Dark-sky sites, long trails, and what fits in a pack.</p><span class="status status--soon"><i class="dot"></i>Pending</span></div>
        <div class="card"><span class="card__idx">[ 05 ]</span><h2 class="card__title h-md">Rock climbing</h2><p class="card__body">Problem solving with consequences.</p><span class="status status--soon"><i class="dot"></i>Pending</span></div>
        <div class="card"><span class="card__idx">[ 06 ]</span><h2 class="card__title h-md">Travel, music &amp; film</h2><p class="card__body">Places worth the drive, records worth the shelf, films worth rewatching.</p><span class="status status--soon"><i class="dot"></i>Pending</span></div>
      </div>
    </div>
  </section>

  <section class="section">
    <div class="wrap">
      <div class="empty">
        <div class="empty__icon">&#9633;</div>
        <h2>No images yet</h2>
        <p>
          Drop image files into <span class="mono" style="color:var(--fg-2)">/img/gallery/</span> and add a
          <span class="mono" style="color:var(--fg-2)">&lt;figure class="shot" data-zoom&gt;</span> entry to
          this page. The lightbox and responsive grid already work.
        </p>
      </div>

      <!-- Template entry. Duplicate one of these per image.
      <div class="shots" style="margin-top:30px">
        <figure class="shot" data-zoom>
          <img src="/img/gallery/example.jpg" width="1200" height="800" loading="lazy" decoding="async" alt="Describe the image">
          <figcaption>Caption, date</figcaption>
        </figure>
      </div>
      -->
    </div>
  </section>
"""




# ==================================================================
#  MISC holding screen  (served while MISC_LIVE is False)
# ==================================================================
MISC_SOON = """
  <section class="hero">
    <div class="wrap">
      <h1 class="h-xl">Under construction<span class="caret">_</span></h1>
      <div class="btn-row" style="margin-top:30px">
        <a class="btn" href="/">Home</a>
      </div>
    </div>
  </section>
"""


# ==================================================================
#  404
# ==================================================================
NOTFOUND = """
  <section class="hero">
    <div class="wrap">
      <p class="eyebrow"><b>404</b> Not found</p>
      <h1 class="h-xl">Signal lost<span class="caret">_</span></h1>
      <p class="lede">That page does not exist, or it moved.</p>
      <div class="btn-row" style="margin-top:30px">
        <a class="btn btn--primary" href="/">Back to start</a>
      </div>
    </div>
  </section>
"""


# ==================================================================
#  BUILD
# ==================================================================
if __name__ == "__main__":
    print("building pages...")
    page("misc/index.html", title="Misc / Matthew Saunders",
         desc=("Astrophotography, aerospace, computer building, camping, hiking, climbing, music and film, "
               "plus the photographs that come out of them.") if MISC_LIVE else "Under construction.",
         body=MISC if MISC_LIVE else MISC_SOON,
         canonical="https://msaunders.dev/misc/", trail=[("Misc", None)],
         noindex=not MISC_LIVE)

    page("404.html", title="404 / Matthew Saunders",
         desc="Page not found.", body=NOTFOUND,
         canonical="https://msaunders.dev/404.html", noindex=True, trail=[("404", None)])
    stamp_assets()
    print("done.")
